config/routes.rb
ConnectWithSoundCloudDemo::Application.routes.draw do
  root :to => "welcome#index"

  match '/you',           :to => 'welcome#show',    :as => :you
  match '/you/update',    :to => 'welcome#update',  :as => :you_update

  match 'follow/:id',      :to => 'welcome#follow',   :as => :follow

  match '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  match '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  match '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect
end

app/models/user.rb
class User < ActiveRecord::Base
  # Please don't use these keys.
  # You can register your own app: http://soundcloud.com/you/apps
  # http://soundcloud.com/you/apps/localhost-3001/edit
  #SOUNDCLOUD_CLIENT_ID     = "BXnNn9AjpkQVs8SMnri8g"
  #SOUNDCLOUD_CLIENT_SECRET = "FlhLpivGUdRZMszLxlQ3w1Xl70hSMvH39ILze9748"
  # http://soundcloud.com/you/apps/connect-with-soundcloud-rails-demo
  SOUNDCLOUD_CLIENT_ID     = "fa120c2f477a3118927cf6ae273876f8"
  SOUNDCLOUD_CLIENT_SECRET = "db906bed5f3271c72302fb40c866e491"

  def self.soundcloud_client(options={})
    options = {
      :client_id     => SOUNDCLOUD_CLIENT_ID,
      :client_secret => SOUNDCLOUD_CLIENT_SECRET,
    }.merge(options)

    Soundcloud.new(options)
  end
  
  
  def soundcloud_client(options={})
    options= {
      :expires_at    => soundcloud_expires_at,
      :access_token  => soundcloud_access_token,
      :refresh_token => soundcloud_refresh_token
    }.merge(options)
    
    client = self.class.soundcloud_client(options)
    
    # define a callback for successful token exchanges
    # this will make sure that new access_tokens are persisted once an existing 
    # access_token expired and a new one was retrieved from the soundcloud api
    client.on_exchange_token do
      self.update_attributes!({
        :soundcloud_access_token  => client.access_token,
        :soundcloud_refresh_token => client.refresh_token,
        :soundcloud_expires_at    => client.expires_at,
      })
    end
    
    client
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :login_from_session
  
  def logged_in?
    !!current_user
  end
  
  def current_user
    @current_user
  end
  
  def login_as(user)
    @current_user = user
    session[:current_user_id] = user.try(:id)
  end

  def login_from_session
    @current_user = User.find_by_id(session[:current_user_id])
  end
end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
  def connect
    redirect_to soundcloud_client.authorize_url(:display => "popup")
  end

  def connected
    if params[:error].nil?
      soundcloud_client.exchange_token(:code => params[:code])
      me = soundcloud_client.get("/me")
      tmp = soundcloud_client.get("/me/tracks").first
      track = ""
      if tmp
        track = tmp.stream_url
      else
        track = soundcloud_client.get("/me/favorites").first.stream_url
      end

      avatar =  me.avatar_url
      avatar = avatar.sub 'large', 't300x300'

      login_as User.find_or_create_by_soundcloud_user_id({
        :soundcloud_user_id  => me.id,
        :soundcloud_username => me.username,
        :soundcloud_avatar => avatar,
        :soundcloud_track => track
      })

      current_user.update_attributes!({
        :soundcloud_access_token  => soundcloud_client.access_token,
        :soundcloud_refresh_token => soundcloud_client.refresh_token,
        :soundcloud_expires_at    => soundcloud_client.expires_at,
        :soundcloud_avatar => avatar,
        :soundcloud_track => track
      })
    end
    render :layout => false
  end

  def disconnect
    login_as nil
    redirect_to root_path
  end
  
private

  def soundcloud_client
    return @soundcloud_client if @soundcloud_client
    @soundcloud_client = User.soundcloud_client(:redirect_uri  => soundcloud_connected_url)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all;
    #@tracks = current_user.soundcloud_client.get("/me/tracks").first
  end

  def show
    @tracks = current_user.soundcloud_client.get("/me/tracks", :limit => 5)
    @me     = current_user.soundcloud_client.get("/me")
  end

  def update
    res = current_user.soundcloud_client.put("/me", :user => {:description => params[:description]})
    redirect_to :action => :show
  end

  def follow
    if logged_in? 
      puts "FOLLOW" 
      puts params[:id]
      current_user.soundcloud_client.put("/me/followings/"+ params[:id])
    end
    redirect_to action: "index"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stereobuzz</title>
  <!--<script src="http://connect.soundcloud.com/base.js"></script>-->
  <%= stylesheet_link_tag 'application', 'soundcloud' %>
  <%= javascript_include_tag 'jquery-1.5.min', 'connect', 'application', 'soundcontroller' %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Comfortaa:300' rel='stylesheet' type='text/css'>


  <%= csrf_meta_tag %>
</head>
<body>
  <div class="wrapper container">
    <%= yield %>
  </div>

 <%= javascript_include_tag 'spacemod' %>

 </body>
</html>

app/views/soundcloud/connected.html.erb
<!DOCTYPE html>
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Connect with SoundCloud</title>
  </head>
  <body onload="window.opener.SC.Connect.popupCallback(window)">
    <b style="width: 100%; text-align: center;">This popup should automatically close in a few seconds<b>
  </body>
</html>

app/views/welcome/index.html.erb
<%if logged_in? %>
  
  <audio class="vinyl" preload="auto" autoplay autobuffer loop >
    <source src="vinyl.wav">
  </audio>

  <div class="space-frame" data-exit="fadeOut zoomOut" data-duration="1.3">
        <section class="space-inner-frame" style"opacity:0;">
              <h2 >Scroll to Explore</h2>
        </section>
  </div>
  <% @users.each do |user| %>
    <% unless user == current_user %>
      <div class="space-frame" data-enter="fadeIn slideInBottom" data-exit="fadeOut zoomOut" data-duration="2">
          <section class="space-inner-frame">
              <!-- <%= image_tag user.soundcloud_avatar %> -->
              <img src= <%= user.soundcloud_avatar%> onerror="imageError(this)"> 
              <h2> <%= user.soundcloud_username %></h2>

              <%= button_to 'Follow', follow_path(user.soundcloud_user_id) %> 
          <!--   <button onclick="follow(<%= user.soundcloud_user_id %>, &quot<%= follow_path(user.soundcloud_user_id) %>&quot)">Follow</button>  -->

              <audio class="audioplayer" src=<%= user.soundcloud_track %><%= "?client_id=fa120c2f477a3118927cf6ae273876f8" %> preload="auto" autoplay loop></audio>
          </section>
      </div>
    <%else%>
    <% end -%>

  <% end -%>
  <div class="space-frame disconnect" data-enter="fadeIn slideInBottom" data-exit="fadeOut zoomOut" data-duration="1.3">
          <section class="space-inner-frame">
          </section>

      </div>
<%else%>
  <div class="space-frame" data-exit="fadeOut zoomOut" data-duration="1.3">
        <section class="space-inner-frame connect-frame" style"opacity:0;" >
        <h1>STEREOBUZZ</h1>
        <h2>-Dive into music</h2>
       
        <div class="connect-with-soundcloud <%= "connected" if logged_in? %>">
          <%= link_to "Connect With SoundCloud ",    soundcloud_connect_path, :class => "connect" %>
        </div>
        </section>
  </div>

<% end -%>

<script>
  function imageError (element) {
    element.onerror='';
    element.src= "http://lorempixel.com/g/300/300/"
  }
</script>

<div class="connect-with-soundcloud <%= "connected" if logged_in? %>">
  <%= link_to "Disconnect From SoundCloud", soundcloud_disconnect_path, :class => "disconnect" %>
 

  <span class="current-user">
    <span class="username">User: <%= current_user.soundcloud_username if logged_in? %></span>
  </span>
</div>

<span class="madeBy">Made with <i class="fa fa-soundcloud"></i>, by <a href="https://twitter.com/david_naas"><strong>@davidnaas</strong></a></span>


<div class="visible-when-logged-in <%= "hidden" unless logged_in? %>"">
</div>

<!-- Basic User Info         -->
<!-- Update User description -->
<!-- List of Tracks          -->

app/views/welcome/show.html.erb
<div class="infos">
  <div class="details">
    <b>Your SoundCloud User Infos:</b>
    <ul>
      <li>Username: <%= @me.username %></li>
      <li>Fullname: <%= @me.full_name %></li>
      <li>Location: <%= @me.city %>, <%= @me.country %></li>
    </ul>
  </div>
  <%= image_tag(@me.avatar_url, :class => "avatar") %>
  
</div>

<div class="description">
  <% form_tag you_update_path, :method => "post" do %>
    <b>Description:</b>
    <textarea name="description"><%= @me.description %></textarea>
    <input type="submit" value="update" />
    <span class="warning">this will change your SoundCloud profile description!</span>
  <% end %>
</div>

<div class="tracks">
  <b>Your 5 latest tracks</b>
  <ul>
    <% @tracks.each do |track| %>
      <li><%= link_to track.title, track.permalink_url %></li>
    <% end %>
  </ul>
</div>